services:
  ps_app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - ps_mysql
    volumes:
      - .:/app
      
  ps_mysql:
    image: mysql:8
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/products.sql:/docker-entrypoint-initdb.d/products.sql  

volumes:
  mysql-data: